version: '3.7'
services:
  deadline-mysql-1:
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=pass





